name: Build Notelify Releases

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: notelify-linux
          - os: windows-latest
            artifact_name: notelify-windows.exe
          - os: macos-latest
            artifact_name: notelify-mac

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile C++ Code
        run: |
          c++ -std=c++17 -O2 main.cpp -o ${{ matrix.artifact_name }}

      - name: Upload Binary to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
